### ISSUE TITLE
HPO.db not found. Trouble loading clusterProfiler.

### ISSUE THREAD

**Issue by GeorgiiVdovin** [YuLab-SMU/clusterProfiler#611] opened 2023-07-30 15:31 UTC
Hello, I am having trouble launching the package. Running both in R 4.3.0 and 4.3.1 gives the same result.

```R
suppressPackageStartupMessages({if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager") 
  library(clusterProfiler)})
```

Error: package or namespace load failed for ‘clusterProfiler’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘HPO.db’
8.	stop(msg, call. = FALSE, domain = NA)
7.	value[[3L]](cond)
6.	tryCatchOne(expr, names, parentenv, handlers[[1L]])
5.	tryCatchList(expr, classes, parentenv, handlers)
4.	tryCatch({ attr(package, "LibPath") <- which.lib.loc ns <- loadNamespace(package, lib.loc) env <- attachNamespace(ns, pos = pos, deps, exclude, include.only) ...
3.	library(clusterProfiler)
2.	withCallingHandlers(expr, packageStartupMessage = function(c) tryInvokeRestart("muffleMessage"))
1.	suppressPackageStartupMessages({ if (!require("BiocManager", quietly = TRUE)) install.packages("BiocManager") library(dplyr) ...

The following didn't fix it:

'''R 
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("HPO.db")
''' 

'''R

if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

# The following initializes usage of Bioc devel
BiocManager::install(version='devel')

BiocManager::install("HPO.db")

'''

'''R

remotes::install_github("YuLab-SMU/HPO.db")

'''
Installing package(s) 'HPO.db'
Warning: downloaded length 0 != reported length 0Warning: cannot open URL 'https://bioconductor.org/packages/3.18/data/annotation/bin/windows/contrib/4.3/PACKAGES.rds': HTTP status was '404 Not Found'Warning: downloaded length 0 != reported length 0Warning: cannot open URL 'https://bioconductor.org/packages/3.18/data/annotation/bin/windows/contrib/4.3/PACKAGES.gz': HTTP status was '404 Not Found'Warning: downloaded length 0 != reported length 0Warning: cannot open URL 'https://bioconductor.org/packages/3.18/data/experiment/bin/windows/contrib/4.3/PACKAGES.rds': HTTP status was '404 Not Found'Warning: downloaded length 0 != reported length 0Warning: cannot open URL 'https://bioconductor.org/packages/3.18/data/experiment/bin/windows/contrib/4.3/PACKAGES.gz': HTTP status was '404 Not Found'Warning: downloaded length 0 != reported length 0Warning: cannot open URL 'https://bioconductor.org/packages/3.18/workflows/bin/windows/contrib/4.3/PACKAGES.rds': HTTP status was '404 Not Found'Warning: downloaded length 0 != reported length 0Warning: cannot open URL 'https://bioconductor.org/packages/3.18/workflows/bin/windows/contrib/4.3/PACKAGES.gz': HTTP status was '404 Not Found'Warning: downloaded length 0 != reported length 0Warning: cannot open URL 'https://bioconductor.org/packages/3.18/books/bin/windows/contrib/4.3/PACKAGES.rds': HTTP status was '404 Not Found'Warning: downloaded length 0 != reported length 0Warning: cannot open URL 'https://bioconductor.org/packages/3.18/books/bin/windows/contrib/4.3/PACKAGES.gz': HTTP status was '404 Not Found'installing the source package ‘HPO.db’

trying URL 'https://bioconductor.org/packages/3.18/data/annotation/src/contrib/HPO.db_0.99.2.tar.gz'
Content type 'application/x-gzip' length 24377 bytes (23 KB)
downloaded 23 KB

* installing *source* package 'HPO.db' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning: Couldn't set cache size: database disk image is malformed
Use `cache_size` = NULL to turn off this warning.
Warning: Couldn't set synchronous mode: database disk image is malformed
Use `synchronous` = NULL to turn off this warning.
Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
  call: NULL
  error: database disk image is malformed
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/123/AppData/Local/R/win-library/4.3/HPO.db'

Could you please help me further?

R version 4.3.0 (2023-04-21 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] splines   stats4    stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] scran_1.29.1                scuttle_1.11.0              SingleCellExperiment_1.23.0
 [4] org.Mm.eg.db_3.17.0         org.Hs.eg.db_3.17.0         shiny_1.7.4.1              
 [7] pcaExplorer_2.27.1          viridisLite_0.4.2           xlsx_0.6.5                 
[10] data.table_1.14.8           readxl_1.4.3                EnhancedVolcano_1.19.0     
[13] ggrepel_0.9.3               AnnotationDbi_1.63.2        biomaRt_2.57.1             
[16] RColorBrewer_1.1-3          pheatmap_1.0.12             DESeq2_1.41.6              
[19] SummarizedExperiment_1.31.1 Biobase_2.61.0              MatrixGenerics_1.13.1      
[22] matrixStats_1.0.0           GenomicRanges_1.53.1        GenomeInfoDb_1.37.2        
[25] IRanges_2.35.2              S4Vectors_0.39.1            BiocGenerics_0.47.0        
[28] lubridate_1.9.2             forcats_1.0.0               stringr_1.5.0              
[31] purrr_1.0.1                 readr_2.1.4                 tibble_3.2.1               
[34] ggplot2_3.4.2               tidyverse_2.0.0             tidyr_1.3.0                
[37] dplyr_1.1.2                 BiocManager_1.30.21.1      

loaded via a namespace (and not attached):
  [1] bitops_1.0-7              HDO.db_0.99.1             httr_1.4.6               
  [4] webshot_0.5.5             doParallel_1.0.17         Rgraphviz_2.45.0         
  [7] tools_4.3.0               utf8_1.2.3                R6_2.5.1                 
 [10] DT_0.28                   lazyeval_0.2.2            withr_2.5.0              
 [13] prettyunits_1.1.1         gridExtra_2.3             cli_3.6.1                
 [16] TSP_1.2-4                 topGO_2.53.0              genefilter_1.83.1        
 [19] AnnotationForge_1.43.3    limma_3.57.6              rstudioapi_0.15.0        
 [22] RSQLite_2.3.1             generics_0.1.3            GOstats_2.67.1           
 [25] crosstalk_1.2.0           dendextend_1.17.1         GO.db_3.17.0             
 [28] Matrix_1.6-0              fansi_1.0.4               abind_1.4-5              
 [31] lifecycle_1.0.3           yaml_2.3.7                edgeR_3.43.7             
 [34] SparseArray_1.1.11        BiocFileCache_2.9.1       grid_4.3.0               
 [37] blob_1.2.4                promises_1.2.0.1          dqrng_0.3.0              
 [40] crayon_1.5.2              shinydashboard_0.7.2      lattice_0.21-8           
 [43] beachmat_2.17.14          cowplot_1.1.1             annotate_1.79.0          
 [46] xlsxjars_0.6.1            KEGGREST_1.41.0           pillar_1.9.0             
 [49] knitr_1.43                metapod_1.9.0             codetools_0.2-19         
 [52] glue_1.6.2                remotes_2.4.2.1           vctrs_0.6.2              
 [55] png_0.1-8                 cellranger_1.1.0          gtable_0.3.3             
 [58] assertthat_0.2.1          cachem_1.0.8              xfun_0.39                
 [61] S4Arrays_1.1.5            mime_0.12                 survival_3.5-5           
 [64] seriation_1.5.1           rJava_1.0-6               iterators_1.0.14         
 [67] statmod_1.5.0             bluster_1.11.3            ellipsis_0.3.2           
 [70] Category_2.67.0           bit64_4.0.5               threejs_0.3.3            
 [73] progress_1.2.2            filelock_1.0.2            rprojroot_2.0.3          
 [76] irlba_2.3.5.1             colorspace_2.1-0          DBI_1.1.3                
 [79] tidyselect_1.2.0          processx_3.8.2            bit_4.0.5                
 [82] compiler_4.3.0            curl_5.0.1                graph_1.79.0             
 [85] BiocNeighbors_1.19.0      SparseM_1.81              xml2_1.3.5               
 [88] desc_1.4.2                DelayedArray_0.27.10      plotly_4.10.2            
 [91] scales_1.2.1              RBGL_1.77.1               callr_3.7.3              
 [94] NMF_0.26                  rappdirs_0.3.3            digest_0.6.31            
 [97] shinyBS_0.61.1            rmarkdown_2.23            ca_0.71.1                
[100] XVector_0.41.1            htmltools_0.5.5           pkgconfig_2.0.3          
[103] base64enc_0.1-3           sparseMatrixStats_1.13.0  dbplyr_2.3.3             
[106] fastmap_1.1.1             rlang_1.1.1               htmlwidgets_1.6.2        
[109] DelayedMatrixStats_1.23.0 jsonlite_1.8.7            BiocParallel_1.35.3      
[112] GOSemSim_2.27.2           BiocSingular_1.17.1       RCurl_1.98-1.12          
[115] magrittr_2.0.3            GenomeInfoDbData_1.2.10   munsell_0.5.0            
[118] Rcpp_1.0.11               viridis_0.6.4             stringi_1.7.12           
[121] zlibbioc_1.47.0           plyr_1.8.8                pkgbuild_1.4.2           
[124] parallel_4.3.0            Biostrings_2.69.2         hms_1.1.3                
[127] locfit_1.5-9.8            ps_1.7.5                  igraph_1.5.0.1           
[130] rngtools_1.5.2            reshape2_1.4.4            ScaledMatrix_1.9.1       
[133] XML_3.99-0.14             evaluate_0.21             tzdb_0.4.0               
[136] foreach_1.5.2             httpuv_1.6.11             heatmaply_1.4.2          
[139] gridBase_0.4-7            rsvd_1.0.5                xtable_1.8-4             
[142] later_1.3.1               memoise_2.0.1             registry_0.5-1           
[145] cluster_2.1.4             timechange_0.2.0          shinyAce_0.4.2           
[148] GSEABase_1.63.0

**Comment by huerqiang** [comment] 2023-08-04 04:50
There should be a network problem with Bioconductor a few days ago, can you install HPO.db successfully now?

**Comment by GeorgiiVdovin** [comment] 2023-08-04 10:43
> There should be a network problem with Bioconductor a few days ago, can you install HPO.db successfully now?

The issue still persists unfortunately; again tried re-installing the package normally from Bioconductor, via developer Bioc as well as directly from github.

`Warning: Couldn't set cache size: database disk image is malformed
Use `cache_size` = NULL to turn off this warning.
Warning: Couldn't set synchronous mode: database disk image is malformed
Use `synchronous` = NULL to turn off this warning.
Error: package or namespace load failed for 'HPO.db':
 .onLoad failed in loadNamespace() for 'HPO.db', details:
  call: NULL
  error: database disk image is malformed
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Users/123/AppData/Local/R/win-library/4.3/HPO.db'
Warning messages:
1: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\123\AppData\Local\R\win-library\4.3\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\123\AppData\Local\R\win-library\4.3\vctrs\libs\x64\vctrs.dll: Permission denied
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\123\AppData\Local\R\win-library\4.3\00LOCK\digest\libs\x64\digest.dll to C:\Users\123\AppData\Local\R\win-library\4.3\digest\libs\x64\digest.dll: Permission denied
3: In i.p(...) :
  installation of package ‘C:/Users/123/AppData/Local/Temp/Rtmp0ySzjU/file467c3feb3e7b/HPO.db_0.99.2.tar.gz’ had non-zero exit status`

**Comment by guidohooiveld** [comment] 2023-08-15 11:34
It seems you have insufficient user rights; see this part of the warning message: Warning messages: **Permission denied**

Please be sure to start R with (local) administrator rights.

**Comment by BS2018** [comment] 2023-10-27 08:58
Can somebody help?

I am getting the following error when I try to load clusterProfiler after updating R and Rstudio.
> library(clusterProfiler)

Error: package or namespace load failed for ‘clusterProfiler’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘HPO.db’

Note that I have R version 4.3.1 and 2023.09.1 Build 494

Here is my session info:
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)

Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default


locale:
[1] LC_COLLATE=English_United Kingdom.utf8  LC_CTYPE=English_United Kingdom.utf8   
[3] LC_MONETARY=English_United Kingdom.utf8 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.utf8    

time zone: Europe/Oslo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] AnnotationHub_3.10.0 BiocFileCache_2.10.0 dbplyr_2.4.0         BiocGenerics_0.48.0 

loaded via a namespace (and not attached):
 [1] KEGGREST_1.42.0               GOSemSim_2.28.0               remotes_2.4.2.1              
 [4] Biobase_2.62.0                vctrs_0.6.4                   tools_4.3.1                  
 [7] bitops_1.0-7                  generics_0.1.3                stats4_4.3.1                 
[10] curl_5.1.0                    parallel_4.3.1                tibble_3.2.1                 
[13] fansi_1.0.5                   AnnotationDbi_1.64.0          RSQLite_2.3.1                
[16] blob_1.2.4                    pkgconfig_2.0.3               S4Vectors_0.40.0             
[19] lifecycle_1.0.3               GenomeInfoDbData_1.2.11       HDO.db_0.99.1                
[22] compiler_4.3.1                Biostrings_2.70.1             codetools_0.2-19             
[25] httpuv_1.6.12                 GenomeInfoDb_1.38.0           htmltools_0.5.6.1            
[28] RCurl_1.98-1.12               yaml_2.3.7                    interactiveDisplayBase_1.40.0
[31] GO.db_3.18.0                  later_1.3.1                   pillar_1.9.0                 
[34] crayon_1.5.2                  ellipsis_0.3.2                BiocParallel_1.36.0          
[37] cachem_1.0.8                  mime_0.12                     tidyselect_1.2.0             
[40] zip_2.3.0                     digest_0.6.33                 stringi_1.7.12               
[43] dplyr_1.1.3                   purrr_1.0.2                   BiocVersion_3.18.0           
[46] fastmap_1.1.1                 cli_3.6.1                     magrittr_2.0.3               
[49] utf8_1.2.4                    filelock_1.0.2                promises_1.2.1               
[52] rappdirs_0.3.3                bit64_4.0.5                   XVector_0.42.0               
[55] httr_1.4.7                    bit_4.0.5                     png_0.1-8                    
[58] openxlsx_4.2.5.2              memoise_2.0.1                 shiny_1.7.5.1                
[61] IRanges_2.36.0                rlang_1.1.1                   Rcpp_1.0.11                  
[64] xtable_1.8-4                  glue_1.6.2                    DBI_1.1.3                    
[67] BiocManager_1.30.22           rstudioapi_0.15.0             R6_2.5.1                     
[70] zlibbioc_1.48.0

**Comment by guidohooiveld** [comment] 2023-10-27 09:23
Please think twice before cross-posting!

At the Bioconductor support forums you reported the same problem ([here](https://support.bioconductor.org/p/9154873/)), and in that thread the cause of the problem has also been identified (i.e. [bug/compatibility](https://support.bioconductor.org/p/9154865/) issue in `BiocFileCache` with the new version `dbplyr`).

The bug has been fixed in both release and development versions of  `BiocFileCache` `(2.10.1 (Release_3_18) and 2.11.1 (devel/3.19))`. Base on your `sessionInfo()` it is clear that you have still version 2.10.0 of `BioFileCache` installed, so NOT the version that has been fixed. It usually takes 24h (max 48h) before an updated package comes available for download on the Bioconductor site. 
Yet, you can also install the fixed (development) version directly from GitHub: `BiocManager::install("Bioconductor/BiocFileCache")`

**Comment by BS2018** [comment] 2023-10-27 09:53
OK.thank you.

**Comment by Daniela-quijano** [comment] 2023-10-27 16:50
Had the same issue, installing biocfilecache from github seems to be working. Thanks!

**Comment by huerqiang** [comment] 2023-10-27 19:07
https://github.com/YuLab-SMU/DOSE/wiki/The-solution-to-the-failure-of-installing-MPO.db-and-HPO.db-packages

**Comment by BS2018** [comment] 2023-10-28 08:29
**Thank for the help. I was able to install BioCFileCache and Annotation hub worked fine. Note that I was able to install HPO.db and HDO.db. However, I am unable to load clusterProfiler because of this error:

**
> install.packages("MPO.db", dependencies = TRUE, INSTALL_opts = '--no-lock')
Installing package into ‘C:/Users/norik/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘MPO.db’ is not available for this version of R


> BiocManager::install("MPO.db")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories",
package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Bioconductor version 3.18 (BiocManager 1.30.22), R 4.3.1 (2023-06-16 ucrt)
Installing package(s) 'MPO.db'
installing the source package ‘MPO.db’

trying URL 'https://bioconductor.org/packages/3.18/data/annotation/src/contrib/MPO.db_0.99.7.tar.gz'
Content type 'application/x-gzip' length 29300 bytes (28 KB)
downloaded 28 KB

ERROR: failed to lock directory 'C:/Users/norik/AppData/Local/R/win-library/4.3' for modifying
Try removing 'C:/Users/norik/AppData/Local/R/win-library/4.3/00LOCK-MPO.db'

The downloaded source packages are in
	‘C:\Users\norik\AppData\Local\Temp\RtmpesV87Z\downloaded_packages’
Warning message:
In install.packages(...) :
  installation of package ‘MPO.db’ had non-zero exit status

**When I got this error, I copied the MPO folder to win-library/4.3**

**Comment by guidohooiveld** [comment] 2023-10-30 12:57
This message:

```
ERROR: failed to lock directory 'C:/Users/norik/AppData/Local/R/win-library/4.3' for modifying
Try removing 'C:/Users/norik/AppData/Local/R/win-library/4.3/00LOCK-MPO.db'
```

... indicates that you have to manually remove this 'locked' directory first. Do this outside R, for example using Windows Explorer.

I strongly warn against manually copying files; one issue could be that the owner c.q. user rights of the copied files are different compared to when running R, which may result in the exact same behavior you experienced. Also dependencies are then also not properly installed...!

**Comment by BS2018** [comment] 2023-10-30 18:22
Thank you very much. I was able to solve the issues. Now clusterProfiler works fine. enrichKEGG and enrichGO are working for me.

**Comment by wxm18** [comment] 2024-12-30 02:36
MRMix

**Comment by GuangchuangYu** [comment] 2024-12-30 03:11
`HPO.db` is not a dependency of `clusterProfiler` and this thread is out of the scope and should be closed.

**Closed as completed by GuangchuangYu** 2024-12-30 03:11 UTC
