### ISSUE TITLE
download_KEGG {clusterProfiler} cannot get the right pathway map

### ISSUE THREAD

**Issue by china-fix** [YuLab-SMU/clusterProfiler#542] opened 2023-03-01 15:55 UTC
Dear Professor Yu,
i recently meet the problem with 'enrichKEGG()' or 'createKEGGdb::create_kegg_db()' method, which cannot correctly get the pathway map, could it be a bug form the download_KEGG {clusterProfiler} , see the example below:

kk <- enrichKEGG(gene         = gene,
                 organism     = "ece",
                 keyType = "kegg",
                 pAdjustMethod = 'fdr')

Reading KEGG annotation online: "https://rest.kegg.jp/link/ece/pathway"...
**Reading KEGG annotation online: "https://rest.kegg.jp/list/pathway"...**
--> No gene can be mapped....
--> Expected input gene ID: 
--> return NULL...

why **Reading KEGG annotation online: "https://rest.kegg.jp/list/pathway"...**, according to my understanding, it should be **Reading KEGG annotation online: "https://rest.kegg.jp/list/pathway/ece"...** in this case

Kind Regards
Xiao

**Comment by jsnagai** [comment] 2023-03-01 16:42
Also facing the same issue here

**Comment by jsnagai** [comment] 2023-03-01 16:56
@china-fix install the current github version, the issue is addressed in the new commit

devtools::install_github("YuLab-SMU/clusterProfiler")

**Comment by china-fix** [comment] 2023-03-01 17:07
> @china-fix install the current github version, the issue is addressed in the new commit
> 
> devtools::install_github("YuLab-SMU/clusterProfiler")

@jsnagai Thanks bro, i saw a the new commit! cheers!

**Comment by ZZhenQi** [comment] 2023-03-02 10:38
thanks a lot. But i also have a problem is that after kk analysis, dotplot did not works:
> dotplot(kk,showCategory = 20)
Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero

**Comment by ZZhenQi** [comment] 2023-03-02 11:53
> thanks a lot. But i also have a problem is that after kk analysis, dotplot did not works:
> 
> > dotplot(kk,showCategory = 20)
> > Error in ans[ypos] <- rep(yes, length.out = len)[ypos] :
> > replacement has length zero

I found that the dotplot did not plot the result because the qvalue was greater than 0.05

**Comment by yangxinzhi** [comment] 2023-03-03 03:05
But there seems to be a problem, the result is that there is no significant path

**Comment by ZZhenQi** [comment] 2023-03-03 03:58
Yes， I also found that the enrichKEGG@results：p.adjust and q values, the value both were 0.999, may be not correct.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/115803239/222627947-bdddac8b-f5b8-4d62-a4fd-a504979c2382.png">

**Comment by ZZhenQi** [comment] 2023-03-03 04:04
Dear Professor,
Yes， I also found that the enrichKEGG@results：p.adjust and q values, the value both were 0.999, may be not correct. The description is very long including Species Information.

best regards
![image](https://user-images.githubusercontent.com/115803239/222628066-a585fe3e-1667-4c2a-ba5f-c806b78b59bb.png)

**Closed** 2023-03-03 07:09 UTC

**Comment by guidohooiveld** [comment] 2023-03-03 09:15
@ZZhenQi: it is not uncommon to observe identical values of p.adjust and qvalue for variables (genes, proteins, gene sets) despite having a different pvalue. See e.g. this thread at the Bioconductor support forum for more details on this: https://support.bioconductor.org/p/104789/

**Comment by ZZhenQi** [comment] 2023-03-03 09:51
Thank you very much！

**Comment by ZZhenQi** [comment] 2023-03-03 09:51
> @ZZhenQi: it is not uncommon to observe identical values of `p.adjust` and `qvalue` for variables (genes, proteins, gene sets) despite having a different `pvalue`. See e.g. this thread at the Bioconductor support forum for more details on this: https://support.bioconductor.org/p/104789/

Thank you very much！
