### ISSUE TITLE
Error: cannot coerce type 'closure' to vector of type 'any', when run enrichGO 

### ISSUE THREAD

**Issue by Abyss-bai** [YuLab-SMU/clusterProfiler#217] opened 2019-08-08 15:37 UTC
Hi, Prof. Guangchuang and everyone!

I keep getting an error as showed in the title when I run the below codes in RStudio:

```
library(clusterProfiler)

x <- c('90417', '10336', '3627', '150864', '221830', '23521', '23112', '9805', '9491', '79172', '100287482', '9060', '80010', '23404', '8451', '81839', '165215', '3788', '51557', '10780', '5915', '8437', '10463', '9117')

go <- enrichGO(x, OrgDb="org.Hs.eg.db", keyType = "ENTREZID", ont = "BP",
               pvalueCutoff = 0.05, pAdjustMethod = "BH", universe,
               qvalueCutoff = 0.2, readable = FALSE, pool = FALSE)
```

**Error in as.vector(x, mode) : 
  cannot coerce type 'closure' to vector of type 'any'**

I've saw the [#149](https://github.com/GuangchuangYu/clusterProfiler/issues/149) and tried the answer, but the error still occurs. And I've tried both the old and latest version of both R and clusterProfiler. They all didn't work. Could anyone give me a hand, thanks a lot!

**Comment by amcdavid** [comment] 2019-10-23 20:28
Not a developer, but I can replicate this error.  It seems the problem is that there is a function called `universe` in your workspace, likely from a deprecated generic in IRanges.  Perhaps there should be a check that `is.character(universe)` before line 24 of `DOSE:::enricher_internal`.  A workaround is to leave the "universe" argument as missing, but the error is quite cryptic!

**Comment by GuangchuangYu** [comment] 2019-10-24 02:25
fixed in <https://github.com/YuLab-SMU/DOSE/commit/bb454c89ccca08399083624d109bb49c1bf0462d>.

**Closed by GuangchuangYu** 2019-10-24 02:25 UTC

**Comment by WeiYang-BAI** [comment] 2019-11-13 07:54
> Not a developer, but I can replicate this error. It seems the problem is that there is a function called `universe` in your workspace, likely from a deprecated generic in IRanges. Perhaps there should be a check that `is.character(universe)` before line 24 of `DOSE:::enricher_internal`. A workaround is to leave the "universe" argument as missing, but the error is quite cryptic!

Thanks! This works!
